SELECT * FROM pizza_sales;

-- BUSINESS QUESTIONS ASKED 

-- (1) TOTAL REVENUE GENERATED BY DOMINOS


SELECT ROUND(SUM(total_price),2) AS revenue FROM pizza_sales 


-- (2) AVERAGE ORDER VALUE 


SELECT ROUND(SUM(total_price) / COUNT(DISTINCT order_id),2) AS avg_order_val
FROM pizza_sales


-- (3) TOTAL PIZZA SOLD 



SELECT SUM(quantity) AS total_pizza_sold 
FROM pizza_sales



-- (4) TOTAL ORDERS PLACED 


SELECT COUNT(DISTINCT order_id) AS total_orders 
FROM pizza_sales 



-- (5) AVERAGE PIZZA'S PER ORDER 

SELECT * FROM pizza_sales 


SELECT CAST(SUM(quantity)AS DECIMAL (10,2)) / CAST(COUNT( DISTINCT order_id) AS DECIMAL(10,2))AS avg_pizza_per_order 

FROM pizza_sales 


--B. DAILY TREND FOR TOTAL ORDERS 

SELECT * FROM pizza_sales 


SELECT DATENAME(WEEKDAY,order_date) AS weekdays, COUNT(DISTINCT order_id) AS no_of_orders
FROM pizza_sales
GROUP BY DATENAME(WEEKDAY,order_date) 
ORDER BY no_of_orders DESC
 


 --C. MONTHLY TREND ORDER 


 SELECT DATENAME(MONTH, order_date) AS months, COUNT(DISTINCT order_id) AS no_of_orders 

 FROM pizza_sales

 GROUP BY  DATENAME(MONTH, order_date)

 ORDER BY no_of_orders DESC



 --D. PERCENTAGE OF SALES BY PIZZA CATEGORY FOR MONTH OF JANUARY

 SELECT * FROM pizza_sales;


 WITH CTE AS (
 SELECT pizza_category, ROUND(SUM(total_price) ,2 )AS category_price
 FROM pizza_sales
 WHERE MONTH(order_date) = 1
 GROUP BY pizza_category 
 ) 
 SELECT *, category_price / (SELECT ROUND(SUM(total_price),2) FROM pizza_sales WHERE MONTH(order_date)=1)*100 AS percentage_contribution 
 FROM CTE



 -- E. % of Sales by Pizza Size


 SELECT * FROM pizza_sales


 SELECT pizza_size, SUM(total_price) AS sales_per_size,ROUND((SUM(total_price)*100.0/(SELECT SUM(total_price) FROM pizza_sales)),2) AS percentage_contribution

 FROM pizza_sales

 GROUP BY pizza_size

 ORDER BY percentage_contribution DESC


 -- F. Total Pizzas Sold by Pizza Category

 SELECT pizza_category, SUM(quantity)  AS total_sold
 FROM pizza_sales
 GROUP BY pizza_category
 ORDER BY total_sold DESC


 -- G. Top 5 Pizzas by Revenue

 SELECT TOP 5 pizza_name, SUM(total_price) AS total, SUM(quantity) AS total_quantity, SUM(DISTINCT order_id) AS orders  
 FROM pizza_sales 
 GROUP BY pizza_name
 ORDER BY total DESC



 -- H. BOTTOM 5 PIZZA BY REVENUE 


 SELECT TOP 5 pizza_name, SUM(total_price) AS total, SUM(quantity) AS total_quantity, SUM(DISTINCT order_id) AS orders  
 FROM pizza_sales 
 GROUP BY pizza_name
 ORDER BY total ASC


 -- I. Top 5 Pizzas by Quantity


SELECT Top 5 pizza_name, SUM(quantity) AS Total_Pizza_Sold
FROM pizza_sales
GROUP BY pizza_name
ORDER BY Total_Pizza_Sold DESC


-- j. BOTTOM 5 PIZZAS BY QUANTITY

SELECT TOP 5 pizza_name, SUM(quantity) AS Total_Pizza_Sold
FROM pizza_sales
GROUP BY pizza_name
ORDER BY Total_Pizza_Sold ASC


-- K. Top 5 Pizzas by Total Orders


SELECT Top 5 pizza_name, COUNT(DISTINCT order_id) AS Total_Orders
FROM pizza_sales
GROUP BY pizza_name
ORDER BY Total_Orders DESC

-- l. BOTTOM 5 PIZZAS BY QUANTITY 

SELECT Top 5 pizza_name, COUNT(DISTINCT order_id) AS Total_Orders
FROM pizza_sales
GROUP BY pizza_name
ORDER BY Total_Orders ASC

